# Generated by Django 5.2.4 on 2025-07-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('organiser', 'Organiser'), ('participant', 'Participant')], max_length=50),
        ),
    ]
